#pragma once

//#define NO_DEBUG
//#define NO_PRINT 

/* Double tap reset button to enter bootloader */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

//#define ENCODERS_PAD_A { GP28 }
//#define ENCODERS_PAD_B { GP29 }

//#define ENCODER_RESOLUTION 2
//#define ENCODER_DEFAULT_POS 0x3
//#define ENCODER_MAP_KEY_DELAY 10

//#define RGB_MATRIX_LED_COUNT 10

#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0